### ISSUE TITLE
Segfault due to signal handling

### ISSUE THREAD

**Issue by rakyll** [rakyll/gotest#31]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10a172b]

goroutine 17 [running]:
os.(*Process).signal(0x0, 0x111abe0, 0xc000118010, 0x0, 0x0)
	/usr/local/go/src/os/exec_unix.go:56 +0x3b
os.(*Process).Signal(...)
	/usr/local/go/src/os/exec.go:131
main.gotest.func2(0xc00005e1e0, 0xc000078000, 0xc00005e240)
	/Users/jbd/go/src/github.com/rakyll/gotest/main.go:83 +0x5d
created by main.gotest
	/Users/jbd/go/src/github.com/rakyll/gotest/main.go:79 +0x440
```

**Comment by rakyll** [comment]
Closed via https://github.com/rakyll/gotest/pull/35.
